import { useMemo, useState } from 'react'
import { useLiveResource } from '@/lib/use-live-resource'
import { pct, short } from '@/lib/format'
import type { CallerSummary, WalletSummary } from '@/lib/types'
import type { MarketChain } from '@/lib/market-model'
import { ActivityFeed } from './ActivityFeed.web'
import { AppLink, Avatar, Choice, FollowButton, Icon, LiveBadge, Notice, Placeholder, RowSkeleton } from './MarketUI.web'

type Order = 'hits' | 'rate' | 'entries'
export default function Leaderboard() {
  const [kind, setKind] = useState<'wallets' | 'callers'>('wallets')
  const [chain, setChain] = useState<MarketChain>('all')
  const [order, setOrder] = useState<Order>('hits')
  const [query, setQuery] = useState('')
  const wallets = useLiveResource<WalletSummary[]>('/api/leaderboard/wallets?min=2', 30_000, true)
  const callers = useLiveResource<CallerSummary[]>('/api/leaderboard/callers', 30_000, true)
  const [heldWallets, setHeldWallets] = useState<WalletSummary[] | null>(null)
  const ranked = useMemo(() => (wallets.data ?? []).filter(wallet => (chain === 'all' || wallet.chain === chain) && `${wallet.label ?? ''} ${wallet.address}`.toLowerCase().includes(query.toLowerCase()))
    .sort((a, b) => (order === 'rate' ? b.hitRate - a.hitRate : order === 'entries' ? b.tokens - a.tokens : b.hits - a.hits) || b.hits - a.hits || b.tokens - a.tokens), [wallets.data, chain, order, query])
  const people = useMemo(() => [...(callers.data ?? [])].filter(caller => `${caller.profile.handle ?? ''} ${caller.profile.pubkey}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => (order === 'rate' ? b.hitRate - a.hitRate : order === 'entries' ? b.calls - a.calls : b.hits - a.hits) || b.hits - a.hits), [callers.data, order, query])
  const leader = ranked[0]
  const source = kind === 'wallets' ? wallets : callers
  return <div className="lq-page lq-leaderboard"><div className="lq-page-inner">
    <header className="lq-page-heading"><div><div className="lq-eyebrow"><Icon name="trophy" size={14} />Early is a track record.</div><h1>Proof over promises.</h1><p>The wallets and callers who showed up before graduation. Follow their next move.</p></div><LiveBadge /></header>
    {kind === 'wallets' && leader ? <section className="lq-leader-spotlight"><div className="lq-leader-insignia" aria-hidden="true"><Icon name="trophy" size={30} /><span>01</span></div><div className="lq-leader-spotlight-name"><div className="lq-eyebrow">{order === 'hits' ? 'Most graduation hits' : order === 'rate' ? 'Highest hit rate' : 'Most early entries'} · all-time</div><AppLink href={`/wallet/${leader.chain}/${leader.address}`}><h2>{leader.label || short(leader.address, 6)}<Icon name="external" size={16} /></h2></AppLink><p>{leader.chain === 'solana' ? 'Solana' : 'Robinhood Chain'} · on-chain LP wallet</p></div><div className="lq-spotlight-stat"><strong>{leader.hits}</strong><small>graduation hits</small></div><div className="lq-spotlight-stat"><strong>{pct(leader.hitRate)}</strong><small>of {leader.tokens} early entries</small></div><FollowButton kind="wallet" chain={leader.chain} address={leader.address} /></section> : null}
    <div className="lq-market-layout"><section className="lq-panel lq-leaderboard-panel">
      <div className="lq-leader-toolbar"><Choice label="Leaderboard type" value={kind} onChange={value => { setKind(value); setHeldWallets(null) }} options={[{ value: 'wallets', label: 'Liquidity providers', icon: 'wallet' }, { value: 'callers', label: 'Callers', icon: 'users' }]} /><button type="button" className="lq-icon-button" aria-label="Refresh leaderboard" disabled={source.loading} onClick={() => void source.refresh()}><Icon name="refresh" size={14} className={source.loading ? 'lq-is-spinning' : ''} /></button></div>
      <div className="lq-leader-subtoolbar">{kind === 'wallets' ? <Choice label="Leaderboard chain" value={chain} onChange={value => { setChain(value); setHeldWallets(null) }} options={[{ value: 'all', label: 'All chains' }, { value: 'solana', label: 'Solana' }, { value: 'robinhood', label: 'Robinhood' }]} /> : <span className="lq-eyebrow">Calls scored at graduation</span>}<label className="lq-inline-search"><Icon name="search" size={14} /><input value={query} onChange={event => { setQuery(event.target.value); setHeldWallets(null) }} placeholder="Find a wallet" aria-label="Filter leaderboard" /></label></div>
      {source.error ? <Notice onRetry={() => void source.refresh()}>{source.data ? 'The latest refresh failed. Showing the last board.' : 'Could not load the leaderboard.'}</Notice> : null}
      {!source.data && source.loading ? <RowSkeleton rows={8} /> : <div className="lq-leader-table-scroll"><table className="lq-leader-table"><thead><tr><th scope="col">Rank</th><th scope="col">{kind === 'wallets' ? 'Wallet' : 'Caller'}</th>{([{ order: 'hits', label: 'Hits' }, { order: 'entries', label: kind === 'wallets' ? 'Early entries' : 'Calls' }, { order: 'rate', label: 'Hit rate' }] as const).map(column => <th key={column.order} scope="col" aria-sort={order === column.order ? 'descending' : 'none'} className={column.order === 'entries' ? 'lq-entries-column' : ''}><button type="button" onClick={() => { setOrder(column.order); setHeldWallets(null) }}>{column.label}{order === column.order ? ' ↓' : ''}</button></th>)}<th scope="col"><span className="lq-sr-only">Follow</span></th></tr></thead>
        <tbody onMouseEnter={() => setHeldWallets(ranked)} onMouseLeave={() => setHeldWallets(null)} onFocus={() => setHeldWallets(ranked)} onBlur={event => { if (!event.currentTarget.contains(event.relatedTarget)) setHeldWallets(null) }}>
          {kind === 'wallets' ? (heldWallets ?? ranked).map((wallet, index) => <tr key={`${wallet.chain}:${wallet.address}`}><td><span className={`lq-table-rank lq-medal-${index}`}>{index < 3 ? <Icon name="trophy" size={15} /> : null}{String(index + 1).padStart(2, '0')}</span></td><td><AppLink href={`/wallet/${wallet.chain}/${wallet.address}`} className="lq-leader-identity"><Avatar label={wallet.address.slice(-2)} size={32} chain={wallet.chain} /><span><strong>{wallet.label || short(wallet.address, 5)}</strong><small>{wallet.chain === 'solana' ? 'Solana' : 'Robinhood'} · {wallet.adds} adds</small></span></AppLink></td><td className="lq-positive">{wallet.hits}</td><td className="lq-entries-column">{wallet.tokens}</td><td><span className="lq-hit-rate">{pct(wallet.hitRate)}<i><b style={{ width: `${Math.min(100, Math.max(0, wallet.hitRate * 100))}%` }} /></i></span></td><td><FollowButton kind="wallet" chain={wallet.chain} address={wallet.address} compact /></td></tr>)
            : people.map((caller, index) => <tr key={caller.profile.pubkey}><td><span className={`lq-table-rank lq-medal-${index}`}>{String(index + 1).padStart(2, '0')}</span></td><td><AppLink href={`/profile/${caller.profile.pubkey}`} className="lq-leader-identity"><Avatar label={caller.profile.handle || caller.profile.pubkey} size={32} /><span><strong>{caller.profile.handle ? `@${caller.profile.handle}` : short(caller.profile.pubkey)}</strong><small>Token caller</small></span></AppLink></td><td className="lq-positive">{caller.hits}</td><td className="lq-entries-column">{caller.calls}</td><td>{pct(caller.hitRate)}</td><td><FollowButton kind="user" chain="solana" address={caller.profile.pubkey} compact /></td></tr>)}
        </tbody></table></div>}
      {(kind === 'wallets' ? ranked.length === 0 : people.length === 0) && !source.loading ? <Placeholder title={query ? 'No matching profiles' : kind === 'callers' ? 'The next great call could be yours.' : 'Building the board'} body={query ? 'Try a different wallet address or handle.' : kind === 'callers' ? 'Call a token before graduation to build your record.' : 'Wallets qualify after providing liquidity to two tokens before graduation.'} action={<AppLink href="/signals" className="lq-button">Explore tokens <Icon name="arrow" size={14} /></AppLink>} /> : null}
      <footer className="lq-panel-footer"><span>All-time observations · {kind === 'wallets' ? ranked.length : people.length} ranked</span><span>Updates automatically</span></footer>
    </section><aside className="lq-market-rail"><section className="lq-board-explainer"><div className="lq-eyebrow">Know what you’re following</div><h2>Receipts, not reputation.</h2><dl><div><dt>Early entry</dt><dd>A wallet adds liquidity to a token before it graduates.</dd></div><div><dt>A hit</dt><dd>That token later completes its launch curve.</dd></div><div><dt>Hit rate</dt><dd>Graduation hits divided by early entries. Sample size matters.</dd></div></dl><p>Activity records, not a measure of investment returns.</p></section><ActivityFeed compact limit={5} /></aside></div>
  </div></div>
}
